[package]
name = "collatz-dfs"
version = "0.1.0"
edition = "2021"

[dependencies]
par-dfs = { path = "../../", features = ["full"] }
async-trait = "0"
futures = "0"

[dev-dependencies]
similar-asserts = "1"
